name: Health check

on:
  schedule:
    - cron: "05 23 * * *"

jobs:
  health_check:
    name: Health check
    runs-on: ubuntu-20.04
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v3.2
        with:
          url: https://full-stack-open-pokedex-m686.onrender.com/health