name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
    
  tag_release:
    permissions: write-all
    name: Tag release
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
    runs-on: ubuntu-20.04
    steps:
       - uses: actions/checkout@v3
         with:
          fetch-depth: "0"

       - name: Bump version and push tag
         uses: anothrNick/github-tag-action@1.64.0
         env:
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
           DEFAULT_BUMP: patch
           WITH_V: true
    
  notify:
    needs: [tag_release]
    runs-on: ubuntu-20.04
    steps:
      - name: Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          username: Kraken
          description: New version of Pokedex deployed to Render.
          footer: "Severity: Info"
          text: ""
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          username: Kraken
          color: "#ff0f0f"
          description: Something went wronk.
          footer: "Severity: Failure"
          text: ""
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
