name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    name: Simple Deployment Pipeline
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: install
        run: npm install

      - name: lint
        run: npm run eslint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: test:e2e
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000

      - name: Render Deploy Action
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
        run: curl https://api.render.com/deploy/srv-${{ secrets.MY_RENDER_SERVICE_ID}}?key=${{ secrets.MY_RENDER_API_KEY }}

  tag_release:
    permissions: write-all
    name: Tag release
    needs: [simple_deployment_pipeline]
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip')}}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          DEFAULT_BUMP: patch
          WITH_V: true
  notify:
    needs: [tag_release]
    runs-on: ubuntu-20.04
    steps:
      - name: Success
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
          severity: info
          details: New version of Pokedex deployed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Failure
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        with:
          severity: error
          details: Error in CI pipeline.
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
